In [2]:
using LinearAlgebra

In [2]:

"""
    Ls(A, b)

하삼각행렬 A 에 대해 Ax=b 의 해 x 를 구한다.
"""
function Ls(L::Matrix, b::Vector) 
    m, n = size(L)        
    x = zeros(n)
    x[1] = b[1]/L[1, 1]
    for i in 2:n
        x[i] = b[i]
        for j in 1:1:(i-1)
            x[i] -= L[i, j]*x[j]
        end
        x[i] = x[i]/L[i, i]
    end
    return x
end

"""
    Us(A, b)

상삼각행렬 A 에 대해 Ax=b 의 해 x 를 구한다.
"""
function Us(U::Matrix, b::Vector) 
    m, n = size(U)    
        
    x = zeros(n)
    x[n] = b[n]/U[n, n]

    for i in (n-1):-1:1
        x[i] = b[i]
        for j in (i+1):1:n
            x[i] -= U[i, j] * x[j]
        end
        x[i] = x[i]/U[i, i]
    end
    return x
end

Us

In [2]:
L = [1.1 0. 0. 0.; 2. 2. 0. 0.; 3. 0.3 -3. 0.; 5. -2. 3. 7.]
b = [3.1; 5.3; -2.2; 6.0]
x = Ls(L, b)
L*x .- b

4-element Vector{Float64}:
 0.0
 0.0
 1.7763568394002505e-15
 0.0

In [3]:
U = Matrix(transpose(L))
y = Us(U, b)

4-element Vector{Float64}:
 -11.358441558441557
   3.2685714285714287
   1.5904761904761904
   0.8571428571428571

In [3]:
lu([1 3 2; 3 3 1])

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
2×2 Matrix{Float64}:
 1.0       0.0
 0.333333  1.0
U factor:
2×3 Matrix{Float64}:
 3.0  3.0  1.0
 0.0  2.0  1.66667