In [1]:
using BenchmarkTools, LinearAlgebra, Plots
include("triangular.jl")

Ls

In [6]:

L = [1. 0. 0. 0.; 2. 2. 0. 0.; 3. 1. -3. 0.; 5. -2. 3. 7.]
b = [3.1; 5.3; -2.2; 6.0]
x = zeros(Float64, 4)
N = 4
x[1] = b[1]/L[1, 1]
for i in 2:N
    x[i] = b[i]
    for j in 1:(i-1)
        x[i] -= L[i, j]*x[j]
    end
    x[i] = x[i]/L[i, i]
end

In [80]:
A1= [1.0 0 0; 1.0e8 1 0; 1.0e8 1.0e8 1]
b1 = [1.0; 1.0; 1.0]
x1 = Ls(A1, b1)

3-element Vector{Float64}:
  1.0
 -9.9999999e7
  9.9999998e15

In [81]:
A1*x1

3-element Vector{Float64}:
 1.0
 1.0
 0.0

In [84]:
nextfloat(x1[3]), prevfloat(x1[3])

(9.999999800000002e15, 9.999999799999998e15)

In [85]:
A1\b1

3-element Vector{Float64}:
  1.0
 -9.9999999e7
  9.9999998e15

In [97]:
1.0e8-(1.0e8)*(9.9999999e7) + (9.9999999e15+1.0-1.0e8)

0.0

In [94]:
1.0e8-(1.0e8)*(9.9999999e7)

-9.9999998e15

In [93]:
9.9e15-prevfloat(9.9e15)

2.0

In [99]:
9.9e16+1-9.9e16

0.0

In [143]:
n=5
q = [(-10.0)^(-3-i) for i in 1:n]
A3=diagm(q)
for i in 2:n
    for j in 1:i-1
        A3[i, j] = 1.0
    end
end
b3 = [float(i) for i in 1:n]
x=Ls(A3, b3)


5-element Vector{Float64}:
 10000.0
     9.997999999999999e8
    -9.998099969999999e14
    -9.998089971900038e21
     9.998090971709035e29

In [144]:
A3*x

5-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 0.0

In [142]:
b3

5-element Vector{Int64}:
 1
 2
 3
 4
 5