In [1]:
using LinearAlgebra, Plots, BenchmarkTools
include("linalg.jl")

decomposition_qr (generic function with 1 method)

In [2]:
Ac = Float32.([3 4 2 5; 5 3 4 -2; -2 -3 1 0; -2 -3 1 -2])
b = Float32.([3, 2, 1, -2])
l1, u1 = decomposition_lu(Ac)
p4, l4, u4, b4 = decomposition_plu(Ac, b)
x = solve_lu(Ac, b, true)
x2 = solve_lu(Ac, b, false)

4-element Vector{Float32}:
  4.3
 -3.6599998
 -1.3800001
  1.5

In [3]:
decomposition_lu(Ac')

(Float32[1.0 0.0 0.0 0.0; 1.3333334 1.0 0.0 0.0; 0.6666667 -0.18181813 1.0 0.0; 1.6666666 2.8181815 1.8799998 1.0], Float32[3.0 5.0 -2.0 -2.0; 0.0 -3.666667 -0.33333325 -0.33333325; 0.0 0.0 2.2727275 2.2727275; 0.0 0.0 0.0 -2.0])

In [4]:
U = Float64.([1 1 0 0; 1 0 1 0; 0 1 0 1; 0 0 -1 1])
V = gram_schmidt(U)
v1, v2, v3, v4 = V[:,1], V[:,2], V[:,3], V[:,4]
Q, R = decomposition_qr(U)

([0.7071067811865475 0.4082482904638631 -0.28867513459481287 -0.5000000000000001; 0.7071067811865475 -0.4082482904638631 0.28867513459481287 0.5000000000000001; 0.0 0.8164965809277261 0.2886751345948128 0.5000000000000001; 0.0 0.0 -0.8660254037844385 0.49999999999999994], [1.414213562373095 0.7071067811865475 0.7071067811865475 0.0; 0.0 1.2247448713915892 -0.4082482904638631 0.8164965809277261; 0.0 0.0 1.1547005383792515 -0.5773502691896257; 0.0 0.0 0.0 1.0])

In [46]:
S1 = Float64.([1 1 0 1; 1 -1 0 1; 0 1 0 1; 0 0 -1 1])'
S3 = Float64.([1 1 0 1; 1 1 0 1.0e-10; 0 1 0 1; 0 0 -1 1])'
S5 = copy(S1)
S5[:, 2]= S1[:, 2]*1.0e-10

4-element Vector{Float64}:
  1.0e-10
 -1.0e-10
  0.0
  1.0e-10

In [47]:
Q1, R1 = decomposition_qr(S1)
Q2, R2 = qr(S1);
Q3, R3 = decomposition_qr(S3)
Q4, R4 = qr(S3)
Q5, R5 = decomposition_qr(S5)
Q6, R6 = qr(S5)


LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
4×4 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.57735   0.408248   0.707107   0.0
 -0.57735  -0.816497   0.0        0.0
  0.0       0.0        0.0       -1.0
 -0.57735   0.408248  -0.707107   0.0
R factor:
4×4 Matrix{Float64}:
 -1.73205  -5.7735e-11   -1.1547    -0.57735
  0.0       1.63299e-10  -0.408248   0.408248
  0.0       0.0          -0.707107  -0.707107
  0.0       0.0           0.0        1.0

In [77]:
N=50
SS = zeros(Float64, N, N)
while(true)
    SS = rand(N, N)
    if abs(det(SS)) > 1.0e-6
        break
    end
end
Q1, R1 = decomposition_qr(SS);
Q2, R2 = qr(SS);
println(sum(abs.(Q1*R1 .- SS)))
println(sum(abs.(Q2*R2 .- SS)))

1.5150195551219547e-12
6.249040998204669e-13


In [61]:
sum(abs.(Q1*R1 .- SS))

1.401597154310208e-12

In [62]:
sum(abs.(Q2*R2 .- SS))

2.2111999731233567e-13

In [52]:
Q5*R5

4×4 Matrix{Float64}:
 1.0   1.0e-10  3.10696e-16   1.21169e-16
 1.0  -1.0e-10  1.0           9.1108e-17
 0.0   0.0      0.0          -1.0
 1.0   1.0e-10  1.0           1.0

In [53]:
Q6*R6

4×4 Matrix{Float64}:
 1.0   1.0e-10  -2.22045e-16   0.0
 1.0  -1.0e-10   1.0           0.0
 0.0   0.0       0.0          -1.0
 1.0   1.0e-10   1.0           1.0

In [54]:
S2=Matrix(S')

4×4 Matrix{Float64}:
 1.0   1.0  0.0   0.0
 1.0  -1.0  1.0   0.0
 0.0   0.0  0.0  -1.0
 1.0   1.0  1.0   1.0

In [19]:
gram_schmidt(S)

4×4 Matrix{Float64}:
 0.707107  0.0   0.0  NaN
 0.707107  0.0   0.0  NaN
 0.0       1.0   0.0  NaN
 0.0       0.0  -1.0  NaN

In [20]:
Q1

4×4 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.707107   0.0  0.0   0.707107
 -0.707107   0.0  0.0  -0.707107
  0.0       -1.0  0.0   0.0
  0.0        0.0  1.0   0.0

In [27]:
S2=[1 1 0 1; 1 1 0 1; -1 0 0 1; 1 0 1 -1]

4×4 Matrix{Int64}:
  1  1  0   1
  1  1  0   1
 -1  0  0   1
  1  0  1  -1

In [33]:
Q2, R2 = qr(S2)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
4×4 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.5  -0.5   1.66533e-16  -0.707107
 -0.5  -0.5  -1.66533e-16   0.707107
  0.5  -0.5  -0.707107      0.0
 -0.5   0.5  -0.707107      1.11022e-16
R factor:
4×4 Matrix{Float64}:
 -2.0  -1.0  -0.5        0.0
  0.0  -1.0   0.5       -2.0
  0.0   0.0  -0.707107  -7.39557e-32
  0.0   0.0   0.0        3.14018e-16

In [41]:
norm(Q2[:,4])

1.0

In [32]:
Q2

UndefVarError: UndefVarError: Q2 not defined

In [ ]:
Q